name: NPGuys
version: "1.4.0 BETA (Dev build)"
author: Goldob
main: pl.ragecraft.npguys.NPGuys
depend: [Citizens]
softdepend: [Vault, Quests, Quester, Heroes, BarAPI]

commands:
  npguy:
    description: "NPGuy management commands"
    aliases: [npg]
    permission: npguys.manage
    ussage: "Unknown command! Type /npguy for command list!"
  dialogue:
    description: "Dialogue management commands"
    permission: npguys.manage
    ussage: "Unknown command! Type /npguy for command list!"
  npguys:
    description: "Plugin management commands"
    permission: npguys.manage

permissions:
  npguys.*:
    desciption: "Gives access to all NPGuys features"
    default: op
    children:
      npguys.manage.*: true
  npguys.manage.*:
    description: "Gives access to NPGuys management commands"
    children:
      npguys.manage.dialogues: true
      npguys.manage.npc: true
      npguys.manage.commands: true
  npguys.manage:
    description: "You need this to perform any NPGuys commands"
    default: op