conversation:
  distance: 5.0
ui:
  default: "SCOREBOARD"
  npc:
    message_format: "&9[&6NPGuys&9] %npc: &r%msg"
    delay: 20
  player:
    message_format: "&9[&6NPGuys&9] %player: &r%msg"
  configs:
    scoreboard:
      headline: "Your answer"
      use-scrollback: false
    boss_healthbar:
      use-scrollback: false
dialogues:
  default:
    shortcut: "default"
    message: "This is default message."
    npc_response:
      message: "This is default NPC response"
  exit:
    shortcut: "Goodbye!"
    message: "Goodbye, %npc!"
    npc_response:
      message: "Goodbye, %player!"