name: NPGuys
version: "1.5.0 (Dev build)"
author: Goldob
main: goldob.npguys.NPGuys
depend: [Citizens]
softdepend: [Vault, Quests, Quester, Heroes, SkillAPI, BarAPI]

commands:
  npguy:
    description: "NPGuy management commands"
    aliases: [npg]
    permission: npguys.manage
  dialogue:
    description: "Dialogue management commands"
    permission: npguys.manage
  npguys:
    description: "Plugin management commands"
    permission: npguys.manage

permissions:
  npguys.manage:
    description: "You need this to perform any NPGuys commands"
    default: op